version: '3.8'

services:
  monet:
    build:
      context: .
      target: development
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - .env.dev
    depends_on:
      - db
      - dynamodb-admin
      - dynamodb-local
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=monet
      - POSTGRES_PASSWORD=monet
      - POSTGRES_DB=monet_dev
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8004:8000"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8002:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - dynamodb-local
volumes:
  postgres_data:
